# Generated by Django 3.0.4 on 2020-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('deadline', models.DateField(null=True)),
                ('isFinish', models.CharField(default='no', max_length=10)),
                ('priority', models.PositiveIntegerField()),
            ],
        ),
    ]
